version: '3.7'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./observability/prometheus/rules.yml:/etc/prometheus/rules.yml:ro
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./observability/alertmanager/config.yml:/etc/alertmanager/config.yml:ro
    ports:
      - 9093:9093

  uptime-kuma:
    image: louislam/uptime-kuma:1
    ports:
      - 3001:3001
    volumes:
      - uptimekuma-data:/app/data

volumes:
  grafana-storage:
  uptimekuma-data:
