name: Backend Docker Build and Push

on:
  push:
    branches: [main, develop]
    tags: ["v*"]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run type checking
        run: npm run type-check

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-tags: ${{ steps.meta.outputs.tags }}
      image-name: ${{ steps.image-name.outputs.lowercase }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert image name to lowercase
        id: image-name
        run: echo "lowercase=$(echo '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build application
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.image-name.outputs.lowercase }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # platforms: linux/amd64,linux/arm64  # Removed for faster builds
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Verify build and push success
        if: github.event_name != 'pull_request'
        run: |
          echo "Build digest: ${{ steps.build.outputs.digest }}"
          echo "Built tags: ${{ steps.meta.outputs.tags }}"
          echo "Lowercase image name: ${{ steps.image-name.outputs.lowercase }}"

          # Verify the main tag exists
          MAIN_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          echo "Verifying main tag: ${MAIN_TAG}"

          # Wait a moment for image to be available
          sleep 10

          # Check if image exists in registry
          docker manifest inspect "${MAIN_TAG}" || {
            echo "ERROR: Failed to verify pushed image ${MAIN_TAG}"
            echo "Available build outputs:"
            echo "- Digest: ${{ steps.build.outputs.digest }}"
            echo "- Tags: ${{ steps.meta.outputs.tags }}"
            exit 1
          }

          echo "✅ Image successfully built and pushed: ${MAIN_TAG}"

  security-scan:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: read
      security-events: write
      actions: read
      id-token: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get image tag for scanning
        id: scan-tag
        run: |
          # Debug the build outputs first
          echo "🔍 Debug build outputs:"
          echo "Image name: ${{ needs.build.outputs.image-name }}"
          echo "Image digest: ${{ needs.build.outputs.image-digest }}"
          echo "Raw tags output:"
          echo "${{ needs.build.outputs.image-tags }}"
          echo "---"

          # Use the first tag from the actual build output, but clean it up
          BUILT_TAGS="${{ needs.build.outputs.image-tags }}"

          # Extract the first line and trim whitespace
          FIRST_TAG=$(echo "${BUILT_TAGS}" | head -n1 | xargs)

          # If first tag is empty, fallback to constructing the tag
          if [ -z "${FIRST_TAG}" ]; then
            echo "⚠️ No tags found in build output, constructing fallback tag"
            BASE_IMAGE="${{ needs.build.outputs.image-name }}"
            if [ "${{ github.ref }}" = "refs/heads/main" ]; then
              FIRST_TAG="${BASE_IMAGE}:latest"
            else
              BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9._-]/-/g')
              FIRST_TAG="${BASE_IMAGE}:${BRANCH_NAME}"
            fi
          fi

          echo "Selected tag for scanning: ${FIRST_TAG}"
          echo "image-tag=${FIRST_TAG}" >> $GITHUB_OUTPUT

      - name: Verify image exists before scanning
        id: verify-image
        continue-on-error: true
        run: |
          IMAGE_TAG="${{ steps.scan-tag.outputs.image-tag }}"
          echo "🔍 Checking if image exists: ${IMAGE_TAG}"

          # Wait for image propagation in registry
          echo "⏳ Waiting for image propagation..."
          sleep 15

          # Try multiple times with backoff
          MAX_ATTEMPTS=3
          ATTEMPT=1

          while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
            echo "Attempt $ATTEMPT/$MAX_ATTEMPTS to verify image..."
            
            if docker manifest inspect "${IMAGE_TAG}" 2>/dev/null; then
              echo "✅ Image found: ${IMAGE_TAG}"
              echo "image-available=true" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "❌ Image not found on attempt $ATTEMPT"
              if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
                echo ""
                echo "🚨 FINAL ERROR: Image ${IMAGE_TAG} not found after $MAX_ATTEMPTS attempts"
                echo ""
                echo "🔍 Debugging information:"
                echo "Build outputs from previous job:"
                echo "- Image name: ${{ needs.build.outputs.image-name }}"
                echo "- Built tags: ${{ needs.build.outputs.image-tags }}"
                echo "- Digest: ${{ needs.build.outputs.image-digest }}"
                echo ""
                echo "🔍 Registry debugging:"
                echo "Trying to list packages in registry..."
                # Try to see if we can at least reach the registry
                docker manifest inspect ghcr.io/rice-bikes/ricebikesbackend:latest 2>/dev/null || echo "Cannot reach latest tag either"
                echo "image-available=false" >> $GITHUB_OUTPUT
                exit 1
              else
                echo "Waiting 10 seconds before retry..."
                sleep 10
                ATTEMPT=$((ATTEMPT + 1))
              fi
            fi
          done

      - name: Run Trivy vulnerability scanner
        id: trivy-scan
        if: steps.verify-image.outputs.image-available == 'true'
        continue-on-error: true # Don't fail the entire workflow if scan fails
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.scan-tag.outputs.image-tag }}
          format: "sarif"
          output: "trivy-results.sarif"
          skip-files: "**/*.test.js,**/*.spec.js,**/node_modules/**"
          skip-dirs: "node_modules,test,tests"
          exit-code: "0" # Don't fail the build on vulnerabilities
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always() && steps.trivy-scan.outcome == 'success'
        with:
          sarif_file: "trivy-results.sarif"
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Security scan summary
        if: always()
        run: |
          if [ "${{ steps.verify-image.outputs.image-available }}" = "true" ]; then
            if [ "${{ steps.trivy-scan.outcome }}" = "success" ]; then
              echo "✅ Security scan completed successfully"
            else
              echo "⚠️ Security scan failed, but build continues"
              echo "Image was available but scanning encountered issues"
            fi
          else
            echo "⚠️ Security scan skipped - image not available"
            echo "Build completed successfully but image verification failed"
            echo "This may be due to:"
            echo "- Registry propagation delays"
            echo "- Authentication issues"
            echo "- Image tag mismatch"
            echo "- Network connectivity issues"
          fi
